import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//모든 페이지에 보일 html 작성
export default function RootLayout({ children }) {
  const menuItems = [
    {
      icon: "bbb",
      label: "Item 1",
      desc: "Item 1 description",
      link: "https://www.example.com/item1",
    },
    {
      icon: "",
      label: "Item 2",
      desc: "Item 2 description",
      link: "https://www.example.com/item2",
    },
    {
      icon: "",
      label: "Item 3",
      desc: "Item 3 description",
      link: "https://www.example.com/item3",
    },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-white border-gray-200 dark:bg-gray-900">
          <div className=" flex flex-wrap items-center justify-between mx-auto p-4">
            <a href="https://flowbite.com/" className="flex items-center">
              <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">
                oldrookie
              </span>
            </a>
            <button
              data-collapse-toggle="navbar-default"
              type="button"
              className="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
              aria-controls="navbar-default"
              aria-expanded="false"
            >
              <span className="sr-only">Open main menu</span>
              <svg
                className="w-5 h-5"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 17 14"
              >
                <path
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M1 1h15M1 7h15M1 13h15"
                />
              </svg>
            </button>
            <div className="hidden w-full block w-auto" id="navbar-default">
              <ul className="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 flex-row space-x-8 mt-0 border-0 md:bg-white dark:bg-gray-800 dark:bg-gray-900 dark:border-gray-700">
                <li>
                  <a
                    href="#"
                    className="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"
                    aria-current="page"
                  >
                    Home
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                  >
                    About
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                  >
                    Projects
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                  >
                    Contact
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        {/* <Navbar label="Menu" items={menuItems} /> */}
        {/* <Navbar /> */}
        {children}
        <footer className="sm:text-sm bg-white shadow">
          <div className="w-full max-w-screen-xl mx-auto p-4 md:py-8">
            <div className="flex items-center justify-between">
              <a
                href="https://flowbite.com/"
                className="flex items-center mb-4 sm:mb-0"
              ></a>
              <ul className="flex flex-wrap items-center mb-6 text-sm font-medium text-gray-500 sm:mb-0">
                <li>
                  <a href="#" className="mr-4 hover:underline md:mr-6 ">
                    Home
                  </a>
                </li>
                <li>
                  <a href="#" className="mr-4 hover:underline md:mr-6">
                    About
                  </a>
                </li>
                <li>
                  <a href="#" className="mr-4 hover:underline md:mr-6 ">
                    Projects
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:underline">
                    Contact
                  </a>
                </li>
              </ul>
            </div>
            <p className="py-1.5 self-center text-l font-semibold whitespace-nowrap ">
              (주)올드루키
            </p>
            <p className="py-1.5">
              대표이사 한영석 | 사업자등록번호 263-87-01519
            </p>
            <p className="py-1.5">
              주소: 서울시 도봉구 마들로 13길 84, 서울창업허브 창동, 212호 TEL :
              02-2039-3699
            </p>
            <span className="block text-sm text-gray-500 text-center dark:text-gray-400 lg:my-5">
              © 2023{" "}
              <a href="https://flowbite.com/" className="hover:underline">
                ©oldrookie
              </a>
              . All Rights Reserved.
            </span>
          </div>
        </footer>
      </body>
    </html>
  );
}
